services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/data
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: python_app
    ports:
      - "8080:8080"
    depends_on:
      - ollama
  
volumes:
  ollama_data: