services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    volumes:
      - ./ollama_data:/data
    environment:
      OLLAMA_ORIGINS: "*"
    networks:
      - app
    ports:
      - "11435:11434"
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: python_app
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    networks:
      - app
  
volumes:
  ollama_data:

networks:
  app:
